
service: next-train
provider:
  name: aws
  runtime: nodejs4.3
  defaults:
    stage: dev
    region: eu-west-1
  custom:
    webpackIncludeModules: true
functions:
  nextTrain:
    handler: nextTrain.run
plugins:
  - serverless-webpack
